In [2]:
import numpy as np
import pandas as pd

date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

#Working with Dates

In [5]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

**1. Extract year**

In [6]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
115 2018-10-13        5779       13       6       2018
579 2018-08-13        7059       14      31       2018
464 2018-09-26        4895       29       1       2018
640 2018-11-03        3161       21       1       2018
870 2019-08-10        3800       16       2       2019

**2. Extract Month**

In [7]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [8]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

**Extract Days**

In [9]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [10]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [11]:
# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [12]:
# is weekend?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

**Extract week of the year**

In [13]:
date['date_week'] = date['date'].dt.week
date.drop(columns=['product_id','city_id','orders']).head()

<ipython-input-13-035dc9841854>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  date['date_week'] = date['date'].dt.week

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

**Extract Quarter**

In [14]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

**Extract Semester**

In [18]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

**Extract Time elapsed between datesa**

In [16]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2023, 9, 21, 20, 26, 21, 61046)

In [17]:
today - date['date']

0     1381 days 20:26:21.061046
1     1863 days 20:26:21.061046
2     1794 days 20:26:21.061046
3     1496 days 20:26:21.061046
4     1719 days 20:26:21.061046
                 ...
995   1809 days 20:26:21.061046
996   1750 days 20:26:21.061046
997   1598 days 20:26:21.061046
998   1663 days 20:26:21.061046
999   1437 days 20:26:21.061046
Name: date, Length: 1000, dtype: timedelta64[ns]

In [19]:
(today - date['date']).dt.days

0      1381
1      1863
2      1794
3      1496
4      1719
       ...
995    1809
996    1750
997    1598
998    1663
999    1437
Name: date, Length: 1000, dtype: int64

In [20]:
# Months passed
np.round((today -date['date']) / np.timedelta64(1, 'M'),0)

0      45.0
1      61.0
2      59.0
3      49.0
4      57.0
       ...
995    59.0
996    58.0
997    53.0
998    55.0
999    47.0
Name: date, Length: 1000, dtype: float64



---



---



---



---



---

#Working with Times

In [21]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [22]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

**Extract Time part**

In [23]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

**Time difference**

In [24]:
today - time['date']

0     3567 days 19:36:21.061046
1     3431 days 20:46:21.061046
2     3917 days 20:05:21.061046
3     3219 days 19:55:21.061046
4     3616 days 21:15:21.061046
                 ...
995   4206 days 19:36:21.061046
996   3527 days 21:12:21.061046
997   3992 days 20:49:21.061046
998   4108 days 20:52:21.061046
999   3380 days 21:01:21.061046
Name: date, Length: 1000, dtype: timedelta64[ns]

In [25]:
# in seconds
(today - time['date'])/np.timedelta64(1,'s')

0      3.082594e+08
1      2.965132e+08
2      3.385011e+08
3      2.781933e+08
4      3.124989e+08
           ...
995    3.634690e+08
996    3.048091e+08
997    3.449838e+08
998    3.550063e+08
999    2.921077e+08
Name: date, Length: 1000, dtype: float64

In [26]:
# in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      5.137656e+06
1      4.941886e+06
2      5.641685e+06
3      4.636555e+06
4      5.208315e+06
           ...
995    6.057816e+06
996    5.080152e+06
997    5.749729e+06
998    5.916772e+06
999    4.868461e+06
Name: date, Length: 1000, dtype: float64

In [27]:
# in months
(today - time['date'])/np.timedelta64(1,'M')

0      117.220211
1      112.753544
2      128.720082
3      105.787145
4      118.832359
          ...
995    138.214482
996    115.908206
997    131.185202
998    134.996437
999    111.078287
Name: date, Length: 1000, dtype: float64

In [28]:
# in hours
(today - time['date'])/np.timedelta64(1,'h')

0       85627.605850
1       82364.772517
2       94028.089184
3       77275.922517
4       86805.255850
           ...
995    100963.605850
996     84669.205850
997     95828.822517
998     98612.872517
999     81141.022517
Name: date, Length: 1000, dtype: float64